#Compiler
CC = g++

#Object files
OBJS = Vehicle.o test_vehicle.o

#Attica.o Entrance.o List.o Queue.o Segment.o Toll.o 

#Executable
EXEC:	$(OBJS)
	$(CC) -g3 -o p $(OBJS)

#run
run:
	./p 5 10 1 2 2

#Clean
clean:
	rm -f Attica.o Entrance.o List.o Queue.o Segment.o Toll.o Vehicle.o vehicle_test.o  p